'use client';
import {motion} from 'framer-motion';
import {ArrowDown, ArrowUpRight, Award, BookOpen, Download, GraduationCap, Heart, Linkedin, Mail, MapPin, Menu, Phone, Quote, Sparkles, Users, X} from 'lucide-react';
import {useState} from 'react';
import CertificateCarousel from '@/components/CertificateCarousel';
import EducationSection from '@/components/EducationSection';

const skills=['Guest Experience','Hotel Operations','Food & Beverage','Event Coordination','Leadership','Customer Service','Business Foundations','Marketing'];
const achievements=[['Devesse Award · Academics','Top 1 among third-year SAMCIS students, A.Y. 2025–2026, first semester.'],['Skills Olympics Champion','Champion, Wedding Cake Category · Department of Hospitality and Tourism Management, 2025.'],['Tea Concoction Silver Medal','Silver Medal Awardee · Hotel and Restaurant Association of Baguio, 2025.']];
const certifications=[['Business Communications','HP Foundation','May 2026'],['Providing Housekeeping Services','TESDA eTESDA','May 2026'],['Deal with Intoxicated Guests','TESDA eTESDA','May 2026'],['Filipino Brand of Service Excellence Training','Department of Tourism – CAR','March 2026'],['Wedding and Hosting Seminar','Ili-Liwa Events and Management','November 2025'],['Front Office, Food & Beverage and Housekeeping Seminar','Grand Sierra Pines Baguio','April 2025']];
const gallery=['photo-1566073771259-6a8506099945','photo-1542314831-068cd1dbfeeb','photo-1601918774946-25832a4be0d6','photo-1564501049412-61c2a3083791','photo-1551882547-ff40c63fe5fa','photo-1584132967334-10e028bd69f7'];
const nav=['About','Education','Experience','Projects','Awards','Contact'];
function Section({id,kicker,title,children}:{id:string;kicker:string;title:string;children:React.ReactNode}){return <section id={id} className="section"><motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-80px'}}><p className="kicker">{kicker}</p><h2>{title}</h2>{children}</motion.div></section>}
export default function Home(){const [open,setOpen]=useState(false);return <main>
 <nav><a href="#top" className="brand">RB<span>·</span></a><div className="navlinks">{nav.map(n=><a key={n} href={'#'+n.toLowerCase()}>{n}</a>)}</div><a className="navcontact" href="#contact">Let’s connect <ArrowUpRight size={15}/></a><button aria-label="Open menu" className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>{open&&<div className="mobile">{nav.map(n=><a onClick={()=>setOpen(false)} key={n} href={'#'+n.toLowerCase()}>{n}</a>)}</div>}</nav>
 <section id="top" className="hero"><video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster="/images/hero-video-poster.webp" aria-hidden="true" tabIndex={-1}><source src="/videos/hero-hospitality-background.mp4" type="video/mp4"/></video><div className="hero-video-tint"/><div className="hero-video-editorial"/><div className="hero-video-vignette"/><div className="orb one"/><div className="orb two"/><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="hero-copy"><p className="kicker">Hospitality management · Philippines</p><h1>Hello, I’m <em>Rojennieleen</em> Baniaga.</h1><p className="lede">A future hospitality professional dedicated to memorable guest experiences through leadership, innovation, service excellence, and sustainable hospitality.</p><div className="actions"><a className="button" href="#projects">View portfolio <ArrowUpRight size={17}/></a><a className="text-link" href="/resume/rojennieleen-baniaga-resume.pdf"><Download size={16}/> Download resume</a></div></motion.div><motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{delay:.2,duration:.8}} className="portrait"><img src="/images/rojennieleen-baniaga-portrait.jpg" alt="Rojennieleen Baniaga"/><div className="portrait-note"><Sparkles size={17}/><span>Service, considered.</span></div></motion.div></section>
 <Section id="about" kicker="01 — About" title="A thoughtful approach to exceptional hospitality."><div className="about-grid"><p className="big-copy">I am building a career where <em>care and capability</em> meet — transforming everyday interactions into considered, memorable experiences.</p><div><p>My work is shaped by a deep respect for people, cultural awareness, and a calm commitment to high standards. I aspire to contribute to teams that make guests feel understood before they need to ask.</p><div className="values"><span><Heart/>Warmth</span><span><Users/>Collaboration</span><span><Award/>Excellence</span></div></div></div></Section>
 <EducationSection/>
 <Section id="experience" kicker="03 — Strengths" title="Built for the details that matter."><div className="skills">{skills.map((s,i)=><motion.div whileHover={{y:-5}} key={s} className="skill"><span>0{i+1}</span><h3>{s}</h3><ArrowUpRight size={18}/></motion.div>)}</div></Section>
 <Section id="projects" kicker="04 — Projects & leadership" title="Turning organisation into meaningful experiences."><div className="research"><div className="research-main"><BookOpen size={25}/><h3>Hospitality Management Research</h3><p>As Secretary, I made collaboration easier by organising meeting records, creating a clear progress tracker, and synthesising qualitative and quantitative findings.</p><blockquote><Quote size={20}/>The best service starts with careful listening and follows through with thoughtful action.</blockquote></div><div className="achievement-list"><div><Users size={19}/><div><h3>La Lumiere Events Management</h3><p>Events Manager · Led departments through planning and delivery of skills olympics, team building, and corporate events.</p></div></div><div><Users size={19}/><div><h3>SICAP</h3><p>Director for External Affairs · Society of Integrated Commercians for Academic Progress, 2024–2026.</p></div></div><div><Users size={19}/><div><h3>Research focus</h3><p>Perception of commuters in Baguio City to the PUJ Modernization Program, 2025–2026.</p></div></div></div></div></Section>
 <Section id="awards" kicker="05 — Awards & certifications" title="Recognition earned through care and consistency."><div className="research"><div className="achievement-list">{achievements.map(([t,d])=><div key={t}><Award size={19}/><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><div className="cert-grid">{certifications.map(([title,issuer,date])=><div className="cert" key={title}><Award size={18}/><span>{date}</span><h3>{title}</h3><p>{issuer}</p></div>)}</div></div></Section>
 <Section id="certifications" kicker="06 — Credentials" title="Certificates, viewed in full."><p className="certificate-intro">A selected, verified record of academic achievement, service, training, and hospitality practice. Select a certificate to inspect it in full.</p><CertificateCarousel/></Section>
 <Section id="gallery" kicker="07 — Perspective" title="Inspired by places with a point of view."><div className="gallery">{gallery.map((id,i)=><img loading="lazy" key={id} src={`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`} alt={`Hospitality inspiration ${i+1}`}/>)}</div></Section>
 <section id="contact" className="contact"><p className="kicker">06 — Contact</p><h2>Let’s create something <em>remarkable.</em></h2><p>Open to meaningful conversations, opportunities, and collaborations in hospitality and service excellence.</p><p>ROJENNIELEEN B. BANIAGA</p><div className="actions"><span className="text-link"><MapPin size={17}/>180 Upper East Purok 1, Woodsgate, Camp 7, Baguio City</span><a className="text-link" href="tel:+639271643930"><Phone size={17}/>0927 164 3930</a><a className="text-link" href="mailto:rojbaniaga320@gmail.com"><Mail size={17}/>rojbaniaga320@gmail.com</a><a className="text-link" href="https://www.linkedin.com/in/rojennieleen-baniaga/" target="_blank" rel="noopener noreferrer"><Linkedin size={17}/>LinkedIn</a><a className="text-link" href="/resume/rojennieleen-baniaga-resume.pdf"><Download size={16}/> Resume</a></div></section>
 <footer><span>© {new Date().getFullYear()} Rojennieleen Baniaga</span><span>Designed with intention · Philippines</span></footer>
 </main>}
