'use client';

import Image from 'next/image';
import { Award, ExternalLink, GraduationCap, MapPin, Star } from 'lucide-react';
import { motion } from 'framer-motion';

const terms = [['First Semester', '2023–2024', '92.31', ''], ['Second Semester', '2023–2024', '94.89', 'Rank 3'], ['First Semester', '2024–2025', '95.08', 'Rank 4'], ['Second Semester', '2024–2025', '96.06', 'Rank 1'], ['First Semester', '2025–2026', '94.79', 'Rank 1']];
const focus = ['Hospitality Operations', 'Guest Services', 'Food & Beverage', 'Front Office Operations', 'Hospitality Accounting', 'Tourism Management', 'Events Management', 'Service Excellence', 'Business Strategy', 'Leadership'];
const reveal = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-60px' } };

export default function EducationSection() { return <section id="education" className="section education-section"><motion.div {...reveal}><p className="kicker">03 — Education</p><h2>Building a foundation through <em>discipline,</em> leadership, and service.</h2><motion.article className="slu-feature-card" whileHover={{ y: -7 }} transition={{ type: 'spring', stiffness: 250, damping: 22 }}><div className="slu-image"><Image src="/images/slu-maryheights-campus.jpg" alt="Saint Louis University Maryheights Campus in Baguio City" width={1600} height={900} sizes="(max-width: 900px) 100vw, 60vw" priority /><div className="slu-image-overlay"><p>Saint Louis University</p><h3>Bachelor of Science in<br />Hospitality Management</h3><span><MapPin size={14} /> Baguio City, Philippines</span></div></div><div className="slu-feature-copy"><div><p className="eyebrow">Academic profile · 2023 — Present</p><h3>Service-led learning, with standards that travel.</h3><p>Pursuing a Bachelor of Science in Hospitality Management at Saint Louis University, with a focused record in guest experience, operations, tourism, and leadership.</p></div><div className="slu-chips"><span><GraduationCap /> Bachelor&apos;s Degree</span><span><Award /> CHED Full Merit Scholar</span><span><Star /> Dean&apos;s Lister</span><span><MapPin /> Baguio City</span></div><dl className="slu-facts"><div><dt>Expected graduation</dt><dd>2027</dd></div><div><dt>Current standing</dt><dd>BSHM Year 3</dd></div><div><dt>Academic distinction</dt><dd>Rank #1 · AY 2024–2026</dd></div></dl></div></motion.article></motion.div><div className="education-highlights"><motion.a className="ched-card" {...reveal} transition={{ delay: 0 }} href="https://legacy.ched.gov.ph/merit-scholarship/" target="_blank" rel="noopener noreferrer" aria-label="Open the official CHED Merit Scholarship Program website"><span>01</span><ExternalLink aria-hidden="true" size={16} /><h3>CHED Full Merit Scholar</h3><p>Commission on Higher Education (CHED)</p></motion.a>{[['02', 'Dean’s', 'Lister'], ['03', 'Rank #1', 'Second Semester · AY 2024–2025'], ['04', 'Rank #1', 'First Semester · AY 2025–2026']].map(([number, title, detail], index) => <motion.article key={number} {...reveal} transition={{ delay: (index + 1) * .08 }}><span>{number}</span><h3>{title}</h3><p>{detail}</p></motion.article>)}</div><motion.div className="progression" {...reveal}><div className="progression-heading"><p className="kicker">Academic progression</p><p>Semester averages</p></div><ol>{terms.map(([semester, year, average, rank]) => <li key={`${semester}${year}`} className={rank === 'Rank 1' ? 'rank-one' : ''}><span className="progress-dot" /><p>{semester}<small>{year}</small></p><strong>{average}</strong>{rank && <em>{rank}</em>}</li>)}</ol></motion.div><motion.div className="focus-area" {...reveal}><p className="kicker">Academic focus</p><div>{focus.map(item => <span key={item}>{item}</span>)}</div></motion.div></section>; }
